### ISSUE TITLE
Can I use senseglove ROS on the wsl of the Windows?

### ISSUE THREAD

**Issue by PARKBONG** [Adjuvo/senseglove_noetic#2]
Hi, I'm trying to use DK1 with ROS topic on the windows, but I faced this error.

Can I use a senseglove through WSL? (or WSL2 which support GUI)

Thanks.

![image](https://user-images.githubusercontent.com/39259734/202988549-03156854-e707-446e-8ebb-99ceff0183fa.png)

```
bong@DESKTOP-7GI9E9D:/mnt/c/catkin_noetic$ roslaunch senseglove_launch senseglove_finger_distance_demo.launch
... logging to /home/bong/.ros/log/8739ee0e-696c-11ed-964f-047bcba59fd2/roslaunch-DESKTOP-7GI9E9D-549.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://DESKTOP-7GI9E9D:53468/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    senseglove_finger_distance_left (senseglove_finger_distance/senseglove_finger_distance_node)
    senseglove_finger_distance_right (senseglove_finger_distance/senseglove_finger_distance_node)
    startGlove (senseglove_launch/startGlove.sh)

auto-starting new master
process[master]: started with pid [557]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8739ee0e-696c-11ed-964f-047bcba59fd2
process[rosout-1]: started with pid [569]
started core service [/rosout]
process[startGlove-2]: started with pid [572]
process[senseglove_finger_distance_left-3]: started with pid [574]
process[senseglove_finger_distance_right-4]: started with pid [577]
Found path: /mnt/c/catkin_noetic/src/senseglove_original-master/src/hardware_interface/senseglove_hardware/SenseCom/Linux/SenseCom.x86_64
Mono path[0] = '/mnt/c/catkin_noetic/src/senseglove_original-master/src/hardware_interface/senseglove_hardware/SenseCom/Linux/SenseCom_Data/Managed'
Mono config path = '/mnt/c/catkin_noetic/src/senseglove_original-master/src/hardware_interface/senseglove_hardware/SenseCom/Linux/SenseCom_Data/Mono/etc'
INFO: cannot create a symlink to latest log directory: [Errno 17] File exists: '/home/bong/.ros/log/8739ee0e-696c-11ed-964f-047bcba59fd2' -> '/home/bong/.ros/log/latest'
[INFO] [1669015038.387746]: initialize finger distance node
[INFO] [1669015038.404354]: initialize finger distance node
[INFO] [1669015038.435806]: Setting up calibration
[INFO] [1669015038.452289]: Setting up calibration
[WARN] [1669015038.468741]: No calibration data found, using defaults
[WARN] [1669015038.469456]: No calibration data found, using defaults
[INFO] [1669015038.483639]: Done setting up calibration for /senseglove_finger_distance_right/Calibrate
[INFO] [1669015038.498735]: Done setting up calibration for /senseglove_finger_distance_left/Calibrate
Preloaded 'libSGConnect.so'
Preloaded 'ScreenSelector.so'
Logging to /home/bong/.config/unity3d/Sense Glove/SenseCom v1.1.2/Player.log
... logging to /home/bong/.ros/log/8739ee0e-696c-11ed-964f-047bcba59fd2/roslaunch-DESKTOP-7GI9E9D-715.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://DESKTOP-7GI9E9D:53573/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /senseglove/0/rh/controller/hand_state/publish_rate: 30
 * /senseglove/0/rh/controller/hand_state/type: joint_state_contr...
 * /senseglove/0/rh/controller/joint_state/publish_rate: 30
 * /senseglove/0/rh/controller/joint_state/type: joint_state_contr...
 * /senseglove/0/rh/controller/trajectory/allow_partial_joints_goal: True
 * /senseglove/0/rh/controller/trajectory/joints: ['r_thumb_brake',...
 * /senseglove/0/rh/controller/trajectory/publish_rate: 30
 * /senseglove/0/rh/controller/trajectory/type: position_controll...
 * /senseglove/0/rh/robot_description: <?xml version="1....
 * /senseglove/0/rh/robot_state_publisher/publish_frequency: 20

NODES
  /senseglove/0/rh/
    controller_spawner (controller_manager/controller_manager)
    hardware_interface (senseglove_hardware_interface/senseglove_hardware_interface_node)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)

ROS_MASTER_URI=http://localhost:11311

process[senseglove/0/rh/robot_state_publisher-1]: started with pid [731]
process[senseglove/0/rh/controller_spawner-2]: started with pid [732]
process[senseglove/0/rh/hardware_interface-3]: started with pid [733]
[ INFO] [1669015054.007445900]: Selected robot: dk1_right
================================================================================REQUIRED process [senseglove/0/rh/hardware_interface-3] has died!
process has died [pid 733, exit code -11, cmd /mnt/c/catkin_noetic/devel/lib/senseglove_hardware_interface/senseglove_hardware_interface_node dk1_right 0 true __name:=hardware_interface __log:=/home/bong/.ros/log/8739ee0e-696c-11ed-964f-047bcba59fd2/senseglove-0-rh-hardware_interface-3.log].
log file: /home/bong/.ros/log/8739ee0e-696c-11ed-964f-047bcba59fd2/senseglove-0-rh-hardware_interface-3*.log
Initiating shutdown!
================================================================================
[senseglove/0/rh/hardware_interface-3] killing on exit
[senseglove/0/rh/controller_spawner-2] killing on exit
[senseglove/0/rh/robot_state_publisher-1] killing on exit
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/controller_manager/controller_manager", line 35, in <module>
    rospy.init_node('controller_manager', anonymous=True)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 323, in init_node
    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")
rospy.exceptions.ROSInitException: init_node interrupted before it could complete
shutting down processing monitor...
... shutting down processing monitor complete
done
[startGlove-2] process has finished cleanly
log file: /home/bong/.ros/log/8739ee0e-696c-11ed-964f-047bcba59fd2/startGlove-2*.log
```

**Comment by PARKBONG** [comment]
I found that error occurs at the line ` auto current_glove = all_gloves[nr_of_glove_];  // Will be update later`, at the `hardware_builder.cpp`, Is there any solution to solve my problems?

```
std::unique_ptr<senseglove::SenseGloveSetup> HardwareBuilder::createSenseGloveSetup()
{
  const auto robot_name = this->robot_config_.begin()->first.as<std::string>();
  ROS_DEBUG_STREAM("Starting creation of robot " << robot_name);
  // Remove top level robot name key
  YAML::Node config = this->robot_config_[robot_name];
  ROS_DEBUG_STREAM("Size of robot config " << this->robot_config_.size());
  std::vector<SGCore::SG::SenseGlove> all_gloves = SGCore::SG::SenseGlove::GetSenseGloves();
  auto current_glove = all_gloves[nr_of_glove_];  // Will be update later
  ROS_DEBUG_STREAM("creating sensegloves");

  ROS_INFO("0");
  if (SGCore::DeviceList::SenseCommRunning())
  {
    ROS_INFO("Obtained the following gloves: ");
    for (auto& all_glove : all_gloves)
    {
      ROS_INFO("%s", all_glove.ToString().c_str());
    }
    current_glove = correct_glove(all_gloves);
    this->initUrdf(current_glove.GetDeviceType(), current_glove.IsRight());
    ROS_DEBUG_STREAM("Obtained devicetype from glove");
  }
  else
  {
    ROS_ERROR("No Sensegloves connected");
    std::exit(1);
  }
```

**Comment by PARKBONG** [comment]
added +)

The cause of this problem seems to be due to WSL's inability to hold USB connections. Is there a way to connect the glove to the WSL?
![image](https://user-images.githubusercontent.com/39259734/203070223-0ff9458a-3dc9-4e35-8790-0648894e8e35.png)
